# Generated by Django 5.2.6 on 2025-12-08 06:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="About Us", max_length=255)),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "mission_statement",
                    ckeditor.fields.RichTextField(
                        default="To connect job seekers with their dream jobs."
                    ),
                ),
                (
                    "vision_statement",
                    ckeditor.fields.RichTextField(
                        default="To be the leading platform for job seekers worldwide."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Privacy Policy", max_length=255)),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "contact_email",
                    models.EmailField(
                        default="support@jobseeker.com", max_length=254, null=True
                    ),
                ),
                (
                    "contact_address",
                    models.TextField(
                        default="JobSeeker Inc., 123 Career Street, City, Country",
                        null=True,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
