# Generated by Django 5.2.6 on 2025-12-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0012_remove_jobcategory_unique_category_per_employer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("FULL", "Full-time"),
                    ("PART", "Part-time"),
                    ("INTERN", "Internship"),
                    ("REMOTE", "Remote"),
                ],
                default="FULL",
                max_length=200,
                null=True,
            ),
        ),
    ]
