# Generated by Django 5.2.6 on 2025-12-08 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("business_name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("1-10", "1 - 10 employees"),
                            ("11-50", "11 - 50 employees"),
                            ("51-200", "51 - 200 employees"),
                            ("201-500", "201 - 500 employees"),
                            ("500+", "500+ employees"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        default="logo.png",
                        null=True,
                        upload_to="upload_to_logo",
                    ),
                ),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employerprofile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
