# Generated by Django 5.2.6 on 2025-12-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EmployerProfile", "0002_employerprofile_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerprofile",
            name="size",
            field=models.CharField(
                choices=[
                    ("1-10", "1 - 10 employees"),
                    ("11-50", "11 - 50 employees"),
                    ("51-200", "51 - 200 employees"),
                    ("201-500", "201 - 500 employees"),
                    ("500+", "500+ employees"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
